# Generated by Django 5.1.1 on 2024-10-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_supplier_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='plans', to='users.subscriptionfeature'),
        ),
    ]
