# Generated by Django 5.1.1 on 2024-11-01 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscriptionplan_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
    ]
