# Generated by Django 5.1.1 on 2024-11-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pharmacy_address_pharmacy_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
