# Generated by Django 5.1.1 on 2024-10-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('chewable tablet', 'Chewable Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('solution', 'Solution'), ('liquid', 'Liquid'), ('suspension', 'Suspension'), ('elixir', 'Elixir'), ('tonic', 'Tonic'), ('linctus', 'Linctus'), ('pasty', 'Pasty'), ('powder', 'Powder'), ('granules', 'Granules'), ('ointment', 'Ointment'), ('cream', 'Cream'), ('patch', 'Patch'), ('enema', 'Enema'), ('gel', 'Gel'), ('liniment', 'Liniment'), ('suppository', 'Suppository'), ('transdermal patch', 'Transdermal Patch'), ('nasal spray', 'Nasal Spray'), ('topical solution', 'Topical Solution'), ('eye drops', 'Eye Drops')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together={('name', 'manufacturer', 'dosage_form', 'strength')},
        ),
    ]
