# Generated by Django 5.1.1 on 2024-10-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pharmacyproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyproduct',
            name='supplier_price',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
