# Generated by Django 5.1.1 on 2024-10-04 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='core_produc_barcode_5cc7aa_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AddField(
            model_name='medication',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be numeric.', regex='^\\d+$')]),
        ),
    ]
